### ISSUE TITLE
This is not work for me it just errors

### ISSUE THREAD

**Issue by qv-5** [CoderQCFromScraatch/CoBot#2]

**Comment by CoderQCYT** [comment]
get gd.py, mouse, keyboard, pywin32, win32gui

**Comment by qv-5** [comment]
It errors for win32gui

**Comment by qv-5** [comment]
Now its saying AttributeError: module 'gd' has no attribute 'memory'

**Comment by CoderQCYT** [comment]
im on a trip right now so i cant

but pip install gd.py

**Comment by githubpub900** [comment]
go into command prompt then type "py pip install gd.py" and then do it with mouse, keyboard, pywin32 and win32gui

**Comment by qv-5** [comment]
It worked but the gd.memory error still occurs.

**Comment by CoderQCYT** [comment]
i use python 3.9 also trying opening up gd then running it

**Comment by qv-5** [comment]
Not working

**Comment by CoderQCYT** [comment]
sorry but dunno how to fix it
